# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendSms',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
                ('call_back_uri', models.TextField(blank=True)),
                ('reference_id', models.CharField(blank=True, default=b'', max_length=200)),
                ('status', models.IntegerField(blank=True, choices=[(0, b'InProgress'), (1, b'Done'), (2, b'Failed')], default=0)),
                ('dt_added', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
